language: objective-c
osx_image: xcode8
env:
  matrix:
    - DANGER=1
    - TEST="iOS"
    - TEST="OSX"
    - TEST="watchOS"
    - TEST="tvOS"
    - TEST="iOS-Example"
# script: xcodebuild -project CHCubicBezier.xcodeproj -scheme CHCubicBezier -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' -sdk iphonesimulator test